Import("env")



# Compile the config module
SConscript("#/src/engine/config/SConscript", exports="env")

# Compile the app
SConscript("#/src/engine/app/SConscript", exports="env")

# Compile the input
SConscript("#/src/engine/input/SConscript", exports="env")

# Compile the render
SConscript("#/src/engine/render/SConscript", exports="env")

# Compile the igw
SConscript("#/src/engine/igw/SConscript", exports="env")

# Compile the sound module
SConscript("#/src/engine/sound/SConscript", exports="env")

# Compile the physics module
SConscript("#/src/engine/physics/SConscript", exports="env")

# Compile the lua wrapper module
SConscript("#/src/engine/lw/SConscript")
