Import("env")


def source(file):
    return "#/src/engine/input/" + file

env["source_files"] += [
    source("input.cpp"),
    source("input_mapping.cpp"),
    source("input_gamepad.cpp"),
    source("input_gamepad_mapping.cpp")
]