Import("env")

def source(file):
    return "#/src/engine/render/" + file

env["source_files"] += [
    source("render.cpp"),
    source("main_shader.cpp"),
    source("tex2D_array_shader.cpp"),
    source("output_postprocessor.cpp")
]

SConscript("#/src/engine/render/glw/SConscript", exports="env")
SConscript("#/src/engine/render/font/SConscript", exports="env")